name: android_auto_example
description: "Test bench for the android_auto plugin. Runs a head unit and draws Flutter UI on top of it."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  android_auto:
    path: ../packages/android_auto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
