// ignore_for_file: always_specify_types, camel_case_types, non_constant_identifier_names
// ignore_for_file: unused_element, unused_field, public_member_api_docs
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings to the native Android Auto head unit core.
///
/// Generated from linux/src/aa_core.h by package:ffigen. Do not edit by hand.
///
class AaCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AaCoreBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AaCoreBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Frees a string handed out through AaEventCallback. Safe to call with NULL.
  void aa_string_free(ffi.Pointer<ffi.Char> message) {
    return _aa_string_free(message);
  }

  late final _aa_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'aa_string_free',
      );
  late final _aa_string_free = _aa_string_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Frees a buffer handed out through AaAudioCallback. Safe to call with NULL.
  void aa_audio_buffer_free(ffi.Pointer<ffi.Uint8> data) {
    return _aa_audio_buffer_free(data);
  }

  late final _aa_audio_buffer_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>)>>(
        'aa_audio_buffer_free',
      );
  late final _aa_audio_buffer_free = _aa_audio_buffer_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>)>();

  /// The outputs the audio server is offering, so a host app can present a picker.
  ///
  /// One device per line, three tab separated fields: the name to hand to
  /// aa_session_set_audio_device, a human readable description, and "1" for the device the
  /// server would use by default or "0" otherwise. Empty when no audio server can be
  /// reached. The returned string is heap allocated and must be handed back to
  /// aa_string_free.
  ///
  /// Takes no session because it describes the machine rather than a connection, and
  /// blocks for up to a second, so call it from Dart rather than from a hot path.
  ffi.Pointer<ffi.Char> aa_audio_devices() {
    return _aa_audio_devices();
  }

  late final _aa_audio_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'aa_audio_devices',
      );
  late final _aa_audio_devices = _aa_audio_devicesPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// The inputs the audio server is offering, in the same format as aa_audio_devices, for
  /// aa_session_set_microphone_device. Monitors of outputs are left out: they would let a
  /// head unit send the phone its own audio back, which is not what anyone means by a
  /// microphone.
  ffi.Pointer<ffi.Char> aa_microphone_devices() {
    return _aa_microphone_devices();
  }

  late final _aa_microphone_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'aa_microphone_devices',
      );
  late final _aa_microphone_devices = _aa_microphone_devicesPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Creates a session. Does not touch any hardware and does not start any threads yet.
  /// `on_event` may be NULL, though then nothing will ever be reported.
  ffi.Pointer<AaSession> aa_session_create(
    ffi.Pointer<AaConfig> config,
    AaEventCallback on_event,
  ) {
    return _aa_session_create(config, on_event);
  }

  late final _aa_session_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<AaSession> Function(
            ffi.Pointer<AaConfig>,
            AaEventCallback,
          )
        >
      >('aa_session_create');
  late final _aa_session_create = _aa_session_createPtr
      .asFunction<
        ffi.Pointer<AaSession> Function(ffi.Pointer<AaConfig>, AaEventCallback)
      >();

  /// Stops the session if it is running and releases everything. The session pointer is
  /// invalid afterwards. Safe to call with NULL.
  void aa_session_destroy(ffi.Pointer<AaSession> session) {
    return _aa_session_destroy(session);
  }

  late final _aa_session_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<AaSession>)>>(
        'aa_session_destroy',
      );
  late final _aa_session_destroy = _aa_session_destroyPtr
      .asFunction<void Function(ffi.Pointer<AaSession>)>();

  /// Starts the io_context thread pool and begins looking for a phone. Returns 0 on
  /// success, negative on failure. Idempotent.
  int aa_session_start(ffi.Pointer<AaSession> session) {
    return _aa_session_start(session);
  }

  late final _aa_session_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_start',
      );
  late final _aa_session_start = _aa_session_startPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Stops the session and joins its threads. Returns 0 on success. Idempotent.
  int aa_session_stop(ffi.Pointer<AaSession> session) {
    return _aa_session_stop(session);
  }

  late final _aa_session_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_stop',
      );
  late final _aa_session_stop = _aa_session_stopPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// The Flutter texture id carrying the projected video, or -1 while there is no video.
  /// The texture is registered lazily on the first frame.
  int aa_session_texture_id(ffi.Pointer<AaSession> session) {
    return _aa_session_texture_id(session);
  }

  late final _aa_session_texture_idPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_texture_id',
      );
  late final _aa_session_texture_id = _aa_session_texture_idPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Size of the video the phone is actually sending, or 0 before the first frame.
  ///
  /// This is not necessarily the size asked for in AaConfig. The phone picks from the
  /// video configurations service discovery advertised, and it may change mid session
  /// without the texture being rebuilt, so the host app reads it rather than assuming.
  int aa_session_video_width(ffi.Pointer<AaSession> session) {
    return _aa_session_video_width(session);
  }

  late final _aa_session_video_widthPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_video_width',
      );
  late final _aa_session_video_width = _aa_session_video_widthPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  int aa_session_video_height(ffi.Pointer<AaSession> session) {
    return _aa_session_video_height(session);
  }

  late final _aa_session_video_heightPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_video_height',
      );
  late final _aa_session_video_height = _aa_session_video_heightPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Which decoder is running: "VA-API", "software", or "none" before the first frame.
  /// The returned string is heap allocated and must be handed back to aa_string_free.
  ffi.Pointer<ffi.Char> aa_session_video_backend(
    ffi.Pointer<AaSession> session,
  ) {
    return _aa_session_video_backend(session);
  }

  late final _aa_session_video_backendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)
        >
      >('aa_session_video_backend');
  late final _aa_session_video_backend = _aa_session_video_backendPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)>();

  /// Reports a touch to the phone. `points` carries every finger currently down, and
  /// `action_index` is the index within it of the finger this report is about, which only
  /// means anything for AA_TOUCH_POINTER_DOWN and AA_TOUCH_POINTER_UP.
  ///
  /// Returns 0 if the report was queued, -1 on a bad argument, and -2 when there is no
  /// input channel, which is the normal answer whenever a phone is not connected. Nothing
  /// acknowledges an input report, so a caller that ignores the result will never find out
  /// that its taps went nowhere.
  ///
  /// Safe to call from the Dart main isolate: the send is posted onto the channel's own
  /// thread and this returns immediately.
  int aa_session_send_touch(
    ffi.Pointer<AaSession> session,
    int action,
    int action_index,
    ffi.Pointer<AaTouchPoint> points,
    int count,
  ) {
    return _aa_session_send_touch(session, action, action_index, points, count);
  }

  late final _aa_session_send_touchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<AaSession>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<AaTouchPoint>,
            ffi.Int32,
          )
        >
      >('aa_session_send_touch');
  late final _aa_session_send_touch = _aa_session_send_touchPtr
      .asFunction<
        int Function(
          ffi.Pointer<AaSession>,
          int,
          int,
          ffi.Pointer<AaTouchPoint>,
          int,
        )
      >();

  /// Reports one hardware key transition. Down and up are separate calls, as they are on
  /// Android: a phone that gets a down and no up believes the button is still held.
  /// `keycode` must be one of the codes service discovery advertised. Same return values
  /// as aa_session_send_touch.
  int aa_session_send_key(
    ffi.Pointer<AaSession> session,
    int keycode,
    int down,
    int long_press,
  ) {
    return _aa_session_send_key(session, keycode, down, long_press);
  }

  late final _aa_session_send_keyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<AaSession>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('aa_session_send_key');
  late final _aa_session_send_key = _aa_session_send_keyPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int, int, int)>();

  /// Reports rotary encoder movement, in detents, positive clockwise. Sent as a relative
  /// axis rather than a key, which is what makes the phone scroll a list by steps instead
  /// of treating every detent as a button press. Same return values as
  /// aa_session_send_touch.
  int aa_session_send_rotary(ffi.Pointer<AaSession> session, int steps) {
    return _aa_session_send_rotary(session, steps);
  }

  late final _aa_session_send_rotaryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_send_rotary');
  late final _aa_session_send_rotary = _aa_session_send_rotaryPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// 0.0 to 1.0, clamped. Applied in software with a short ramp, so a change mid track is
  /// a fade rather than a click.
  int aa_session_set_audio_volume(
    ffi.Pointer<AaSession> session,
    int stream,
    double volume,
  ) {
    return _aa_session_set_audio_volume(session, stream, volume);
  }

  late final _aa_session_set_audio_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32, ffi.Double)
        >
      >('aa_session_set_audio_volume');
  late final _aa_session_set_audio_volume = _aa_session_set_audio_volumePtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int, double)>();

  double aa_session_audio_volume(ffi.Pointer<AaSession> session, int stream) {
    return _aa_session_audio_volume(session, stream);
  }

  late final _aa_session_audio_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_audio_volume');
  late final _aa_session_audio_volume = _aa_session_audio_volumePtr
      .asFunction<double Function(ffi.Pointer<AaSession>, int)>();

  /// A muted stream is written as silence rather than not written at all, so the stream
  /// clock keeps running and unmuting is instant.
  int aa_session_set_audio_muted(
    ffi.Pointer<AaSession> session,
    int stream,
    int muted,
  ) {
    return _aa_session_set_audio_muted(session, stream, muted);
  }

  late final _aa_session_set_audio_mutedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32, ffi.Int32)
        >
      >('aa_session_set_audio_muted');
  late final _aa_session_set_audio_muted = _aa_session_set_audio_mutedPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int, int)>();

  int aa_session_audio_muted(ffi.Pointer<AaSession> session, int stream) {
    return _aa_session_audio_muted(session, stream);
  }

  late final _aa_session_audio_mutedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_audio_muted');
  late final _aa_session_audio_muted = _aa_session_audio_mutedPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// Which output to play through, as a name from aa_audio_devices. NULL or empty means
  /// the head unit's own speakers: the audio server's default, except that a Bluetooth
  /// device is never chosen for it, because a phone paired for hands free calling moves
  /// that default and the car's speakers are not the phone's to move. Naming a Bluetooth
  /// device here still works. Takes effect on the next buffer of each stream, which for a
  /// stream that is playing is immediately.
  int aa_session_set_audio_device(
    ffi.Pointer<AaSession> session,
    ffi.Pointer<ffi.Char> device,
  ) {
    return _aa_session_set_audio_device(session, device);
  }

  late final _aa_session_set_audio_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>)
        >
      >('aa_session_set_audio_device');
  late final _aa_session_set_audio_device = _aa_session_set_audio_devicePtr
      .asFunction<
        int Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>)
      >();

  /// The device currently selected, or an empty string for the default. Heap allocated,
  /// free with aa_string_free.
  ffi.Pointer<ffi.Char> aa_session_audio_device(
    ffi.Pointer<AaSession> session,
  ) {
    return _aa_session_audio_device(session);
  }

  late final _aa_session_audio_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)
        >
      >('aa_session_audio_device');
  late final _aa_session_audio_device = _aa_session_audio_devicePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)>();

  /// Turns the speakers off without touching the protocol: the phone keeps sending, the
  /// audio callback keeps firing, and nothing is played. For an infotainment system that
  /// routes audio itself, or an app doing its own mixing.
  int aa_session_set_audio_output_enabled(
    ffi.Pointer<AaSession> session,
    int enabled,
  ) {
    return _aa_session_set_audio_output_enabled(session, enabled);
  }

  late final _aa_session_set_audio_output_enabledPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_set_audio_output_enabled');
  late final _aa_session_set_audio_output_enabled =
      _aa_session_set_audio_output_enabledPtr
          .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  int aa_session_audio_output_enabled(ffi.Pointer<AaSession> session) {
    return _aa_session_audio_output_enabled(session);
  }

  late final _aa_session_audio_output_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_audio_output_enabled',
      );
  late final _aa_session_audio_output_enabled =
      _aa_session_audio_output_enabledPtr
          .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Installs the raw PCM tap, or clears it with NULL. See AaAudioCallback.
  int aa_session_set_audio_callback(
    ffi.Pointer<AaSession> session,
    AaAudioCallback on_audio,
  ) {
    return _aa_session_set_audio_callback(session, on_audio);
  }

  late final _aa_session_set_audio_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, AaAudioCallback)
        >
      >('aa_session_set_audio_callback');
  late final _aa_session_set_audio_callback = _aa_session_set_audio_callbackPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, AaAudioCallback)>();

  /// Which audio backend is playing: "PulseAudio", or "none" before the first buffer or on
  /// a machine with no audio server. Heap allocated, free with aa_string_free.
  ffi.Pointer<ffi.Char> aa_session_audio_backend(
    ffi.Pointer<AaSession> session,
  ) {
    return _aa_session_audio_backend(session);
  }

  late final _aa_session_audio_backendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)
        >
      >('aa_session_audio_backend');
  late final _aa_session_audio_backend = _aa_session_audio_backendPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)>();

  /// Times this stream came close to running the speakers dry, since the session started.
  /// The number to watch for "no audible glitches": it should stay at zero.
  int aa_session_audio_underruns(ffi.Pointer<AaSession> session, int stream) {
    return _aa_session_audio_underruns(session, stream);
  }

  late final _aa_session_audio_underrunsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_audio_underruns');
  late final _aa_session_audio_underruns = _aa_session_audio_underrunsPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// Buffers thrown away because the phone sent faster than they could be played.
  int aa_session_audio_dropped(ffi.Pointer<AaSession> session, int stream) {
    return _aa_session_audio_dropped(session, stream);
  }

  late final _aa_session_audio_droppedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_audio_dropped');
  late final _aa_session_audio_dropped = _aa_session_audio_droppedPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// How far behind the head unit the speakers are, in microseconds.
  int aa_session_audio_latency(ffi.Pointer<AaSession> session, int stream) {
    return _aa_session_audio_latency(session, stream);
  }

  late final _aa_session_audio_latencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_audio_latency');
  late final _aa_session_audio_latency = _aa_session_audio_latencyPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// Whether the microphone is open right now, 1 or 0. This is what a "listening" indicator
  /// shows. It reports the state of the device rather than of the channel, so a phone that
  /// has opened the channel but not asked to record reads 0.
  int aa_session_microphone_active(ffi.Pointer<AaSession> session) {
    return _aa_session_microphone_active(session);
  }

  late final _aa_session_microphone_activePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_microphone_active',
      );
  late final _aa_session_microphone_active = _aa_session_microphone_activePtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Peak level of the most recent captured buffer, 0.0 to 1.0, for a level meter. Zero
  /// while the microphone is closed.
  double aa_session_microphone_level(ffi.Pointer<AaSession> session) {
    return _aa_session_microphone_level(session);
  }

  late final _aa_session_microphone_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<AaSession>)>>(
        'aa_session_microphone_level',
      );
  late final _aa_session_microphone_level = _aa_session_microphone_levelPtr
      .asFunction<double Function(ffi.Pointer<AaSession>)>();

  /// Bytes captured since the session was created. Answers "has this machine ever actually
  /// heard anything", which is the question a silent Assistant raises.
  int aa_session_microphone_bytes(ffi.Pointer<AaSession> session) {
    return _aa_session_microphone_bytes(session);
  }

  late final _aa_session_microphone_bytesPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_microphone_bytes',
      );
  late final _aa_session_microphone_bytes = _aa_session_microphone_bytesPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Which input to capture from, as a name from aa_microphone_devices. NULL or empty
  /// means the head unit's own microphone: the audio server's default, except that a
  /// Bluetooth device is never chosen for it, for the reason aa_session_set_audio_device
  /// gives. Takes effect the next time the phone asks for the microphone, because that is
  /// the only moment this is allowed to open anything.
  int aa_session_set_microphone_device(
    ffi.Pointer<AaSession> session,
    ffi.Pointer<ffi.Char> device,
  ) {
    return _aa_session_set_microphone_device(session, device);
  }

  late final _aa_session_set_microphone_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>)
        >
      >('aa_session_set_microphone_device');
  late final _aa_session_set_microphone_device =
      _aa_session_set_microphone_devicePtr
          .asFunction<
            int Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>)
          >();

  /// The input currently selected, or an empty string for the default. Heap allocated, free
  /// with aa_string_free.
  ffi.Pointer<ffi.Char> aa_session_microphone_device(
    ffi.Pointer<AaSession> session,
  ) {
    return _aa_session_microphone_device(session);
  }

  late final _aa_session_microphone_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)
        >
      >('aa_session_microphone_device');
  late final _aa_session_microphone_device = _aa_session_microphone_devicePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)>();

  /// Which capture backend is running: "PulseAudio", or "none" before the first capture or
  /// on a machine with no microphone. Heap allocated, free with aa_string_free.
  ffi.Pointer<ffi.Char> aa_session_microphone_backend(
    ffi.Pointer<AaSession> session,
  ) {
    return _aa_session_microphone_backend(session);
  }

  late final _aa_session_microphone_backendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)
        >
      >('aa_session_microphone_backend');
  late final _aa_session_microphone_backend = _aa_session_microphone_backendPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>)>();

  /// False for day, true for night. Drives the phone's own light and dark theme.
  int aa_session_set_night_mode(ffi.Pointer<AaSession> session, int night) {
    return _aa_session_set_night_mode(session, night);
  }

  late final _aa_session_set_night_modePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_set_night_mode');
  late final _aa_session_set_night_mode = _aa_session_set_night_modePtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// What the car forbids right now, an OR of AaDrivingRestriction bits.
  /// AA_DRIVING_UNRESTRICTED is a parked car, and is what this head unit reports until the
  /// host app says otherwise.
  int aa_session_set_driving_status(
    ffi.Pointer<AaSession> session,
    int restrictions,
  ) {
    return _aa_session_set_driving_status(session, restrictions);
  }

  late final _aa_session_set_driving_statusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_set_driving_status');
  late final _aa_session_set_driving_status = _aa_session_set_driving_statusPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// The car's position. See AaLocation for which fields may be NaN.
  int aa_session_set_location(
    ffi.Pointer<AaSession> session,
    ffi.Pointer<AaLocation> location,
  ) {
    return _aa_session_set_location(session, location);
  }

  late final _aa_session_set_locationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Pointer<AaLocation>)
        >
      >('aa_session_set_location');
  late final _aa_session_set_location = _aa_session_set_locationPtr
      .asFunction<
        int Function(ffi.Pointer<AaSession>, ffi.Pointer<AaLocation>)
      >();

  /// Road speed in metres per second.
  int aa_session_set_speed(
    ffi.Pointer<AaSession> session,
    double metres_per_second,
  ) {
    return _aa_session_set_speed(session, metres_per_second);
  }

  late final _aa_session_set_speedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Double)
        >
      >('aa_session_set_speed');
  late final _aa_session_set_speed = _aa_session_set_speedPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, double)>();

  /// Engine speed in revolutions per minute.
  int aa_session_set_rpm(ffi.Pointer<AaSession> session, double rpm) {
    return _aa_session_set_rpm(session, rpm);
  }

  late final _aa_session_set_rpmPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Double)
        >
      >('aa_session_set_rpm');
  late final _aa_session_set_rpm = _aa_session_set_rpmPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, double)>();

  /// Tank level as a percentage, remaining range in metres, and whether the low fuel
  /// warning is lit.
  int aa_session_set_fuel(
    ffi.Pointer<AaSession> session,
    double level_percent,
    double range_metres,
    int low,
  ) {
    return _aa_session_set_fuel(session, level_percent, range_metres, low);
  }

  late final _aa_session_set_fuelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<AaSession>,
            ffi.Double,
            ffi.Double,
            ffi.Int32,
          )
        >
      >('aa_session_set_fuel');
  late final _aa_session_set_fuel = _aa_session_set_fuelPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, double, double, int)>();

  /// Whether the parking brake is engaged.
  int aa_session_set_parking_brake(
    ffi.Pointer<AaSession> session,
    int engaged,
  ) {
    return _aa_session_set_parking_brake(session, engaged);
  }

  late final _aa_session_set_parking_brakePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_set_parking_brake');
  late final _aa_session_set_parking_brake = _aa_session_set_parking_brakePtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// The selected gear, as the protocol numbers them: 0 neutral, 1 to 10 the numbered
  /// gears, 100 drive, 101 park, 102 reverse.
  int aa_session_set_gear(ffi.Pointer<AaSession> session, int gear) {
    return _aa_session_set_gear(session, gear);
  }

  late final _aa_session_set_gearPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_set_gear');
  late final _aa_session_set_gear = _aa_session_set_gearPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// Heading in degrees clockwise from north. Distinct from the bearing inside a location
  /// fix: this is the direction the car points, which is not the direction it is moving.
  int aa_session_set_compass(
    ffi.Pointer<AaSession> session,
    double bearing_degrees,
  ) {
    return _aa_session_set_compass(session, bearing_degrees);
  }

  late final _aa_session_set_compassPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Double)
        >
      >('aa_session_set_compass');
  late final _aa_session_set_compass = _aa_session_set_compassPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, double)>();

  /// Outside temperature in degrees Celsius and barometric pressure in kilopascals. Either
  /// may be NaN, which leaves that one out.
  int aa_session_set_environment(
    ffi.Pointer<AaSession> session,
    double temperature_celsius,
    double pressure_kpa,
  ) {
    return _aa_session_set_environment(
      session,
      temperature_celsius,
      pressure_kpa,
    );
  }

  late final _aa_session_set_environmentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Double, ffi.Double)
        >
      >('aa_session_set_environment');
  late final _aa_session_set_environment = _aa_session_set_environmentPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, double, double)>();

  /// Total distance travelled, in kilometres.
  int aa_session_set_odometer(
    ffi.Pointer<AaSession> session,
    double kilometres,
  ) {
    return _aa_session_set_odometer(session, kilometres);
  }

  late final _aa_session_set_odometerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Double)
        >
      >('aa_session_set_odometer');
  late final _aa_session_set_odometer = _aa_session_set_odometerPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, double)>();

  /// Whether a toll transponder is in the car.
  int aa_session_set_toll_card(ffi.Pointer<AaSession> session, int present) {
    return _aa_session_set_toll_card(session, present);
  }

  late final _aa_session_set_toll_cardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_set_toll_card');
  late final _aa_session_set_toll_card = _aa_session_set_toll_cardPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// Which sensors the phone has subscribed to, an OR of AaSensor bits, or 0 when no phone
  /// is connected. Never the same question as which ones were advertised: a phone takes
  /// what it wants from the list, and this is the first thing to look at when a value is
  /// being set and nothing on the phone's screen changes.
  int aa_session_sensor_subscriptions(ffi.Pointer<AaSession> session) {
    return _aa_session_sensor_subscriptions(session);
  }

  late final _aa_session_sensor_subscriptionsPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_sensor_subscriptions',
      );
  late final _aa_session_sensor_subscriptions =
      _aa_session_sensor_subscriptionsPtr
          .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Sensor batches written since the session was created. The "did anything actually go
  /// out" number, which is otherwise only answerable by watching the phone's UI.
  int aa_session_sensor_batches(ffi.Pointer<AaSession> session) {
    return _aa_session_sensor_batches(session);
  }

  late final _aa_session_sensor_batchesPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_sensor_batches',
      );
  late final _aa_session_sensor_batches = _aa_session_sensor_batchesPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Installs the metadata callback, or clears it with NULL. See AaMetadataCallback.
  int aa_session_set_metadata_callback(
    ffi.Pointer<AaSession> session,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int32 kind, ffi.Pointer<ffi.Char> json)
      >
    >
    on_metadata,
  ) {
    return _aa_session_set_metadata_callback(session, on_metadata);
  }

  late final _aa_session_set_metadata_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<AaSession>,
            ffi.Pointer<
              ffi.NativeFunction<
                ffi.Void Function(ffi.Int32 kind, ffi.Pointer<ffi.Char> json)
              >
            >,
          )
        >
      >('aa_session_set_metadata_callback');
  late final _aa_session_set_metadata_callback =
      _aa_session_set_metadata_callbackPtr
          .asFunction<
            int Function(
              ffi.Pointer<AaSession>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(ffi.Int32 kind, ffi.Pointer<ffi.Char> json)
                >
              >,
            )
          >();

  /// The latest of one kind, as the same JSON the callback delivers, or an empty string
  /// when the phone has said nothing. For a host app that starts reading after the phone
  /// has already spoken. Heap allocated, free with aa_string_free.
  ffi.Pointer<ffi.Char> aa_session_metadata(
    ffi.Pointer<AaSession> session,
    int kind,
  ) {
    return _aa_session_metadata(session, kind);
  }

  late final _aa_session_metadataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_metadata');
  late final _aa_session_metadata = _aa_session_metadataPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<AaSession>, int)
      >();

  /// Which metadata channels the phone actually opened, an OR of `1 << AaMetadata`, or 0
  /// when no phone is connected. Never the same question as which were advertised, exactly
  /// as with the sensor subscriptions: this is the first thing to look at when nothing is
  /// arriving.
  int aa_session_metadata_channels(ffi.Pointer<AaSession> session) {
    return _aa_session_metadata_channels(session);
  }

  late final _aa_session_metadata_channelsPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_metadata_channels',
      );
  late final _aa_session_metadata_channels = _aa_session_metadata_channelsPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  /// Updates received on one kind since the head unit started. The "is anything coming in"
  /// number.
  int aa_session_metadata_updates(ffi.Pointer<AaSession> session, int kind) {
    return _aa_session_metadata_updates(session, kind);
  }

  late final _aa_session_metadata_updatesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<AaSession>, ffi.Int32)
        >
      >('aa_session_metadata_updates');
  late final _aa_session_metadata_updates = _aa_session_metadata_updatesPtr
      .asFunction<int Function(ffi.Pointer<AaSession>, int)>();

  /// Asks the phone for one node of its media library. `path` is NULL or empty for the
  /// root and otherwise a path out of a previous answer; `start` is the offset into a long
  /// list. The answer arrives as an AA_METADATA_BROWSE update rather than as a return
  /// value, because it is a round trip over USB.
  ///
  /// Returns 0 if the request was queued, -2 when the browser channel is not open, which
  /// is the normal answer whenever no phone is connected or the host app did not advertise
  /// the channel.
  int aa_session_browse(
    ffi.Pointer<AaSession> session,
    ffi.Pointer<ffi.Char> path,
    int start,
  ) {
    return _aa_session_browse(session, path, start);
  }

  late final _aa_session_browsePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<AaSession>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('aa_session_browse');
  late final _aa_session_browse = _aa_session_browsePtr
      .asFunction<
        int Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>, int)
      >();

  /// Tells the phone the user picked `path` in the media browser, which is what makes it
  /// play. Same return values as aa_session_browse.
  int aa_session_browse_select(
    ffi.Pointer<AaSession> session,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _aa_session_browse_select(session, path);
  }

  late final _aa_session_browse_selectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>)
        >
      >('aa_session_browse_select');
  late final _aa_session_browse_select = _aa_session_browse_selectPtr
      .asFunction<
        int Function(ffi.Pointer<AaSession>, ffi.Pointer<ffi.Char>)
      >();

  /// Drives the texture pipeline from a generated pattern instead of a phone, so a host
  /// app can lay its overlay out before any hardware is involved. Started life as M2
  /// scaffolding and earned its keep; the real H.264 path publishes into the same ring.
  int aa_session_start_test_pattern(ffi.Pointer<AaSession> session) {
    return _aa_session_start_test_pattern(session);
  }

  late final _aa_session_start_test_patternPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_start_test_pattern',
      );
  late final _aa_session_start_test_pattern = _aa_session_start_test_patternPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();

  int aa_session_stop_test_pattern(ffi.Pointer<AaSession> session) {
    return _aa_session_stop_test_pattern(session);
  }

  late final _aa_session_stop_test_patternPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AaSession>)>>(
        'aa_session_stop_test_pattern',
      );
  late final _aa_session_stop_test_pattern = _aa_session_stop_test_patternPtr
      .asFunction<int Function(ffi.Pointer<AaSession>)>();
}

final class AaSession extends ffi.Opaque {}

/// Lifecycle states, mirrored by AndroidAutoConnectionState in Dart. Keep the two in
/// step: the integers cross the FFI boundary as-is.
enum AaState {
  AA_STATE_IDLE(0),
  AA_STATE_SEARCHING(1),
  AA_STATE_HANDSHAKING(2),
  AA_STATE_CONNECTED(3),
  AA_STATE_ERROR(4);

  final int value;
  const AaState(this.value);

  static AaState fromValue(int value) => switch (value) {
    0 => AA_STATE_IDLE,
    1 => AA_STATE_SEARCHING,
    2 => AA_STATE_HANDSHAKING,
    3 => AA_STATE_CONNECTED,
    4 => AA_STATE_ERROR,
    _ => throw ArgumentError('Unknown value for AaState: $value'),
  };
}

/// What a touch report describes, mirrored by AndroidAutoTouchAction in Dart and by
/// PointerAction on the wire. All three carry Android's own MotionEvent action
/// constants, so the gaps in the numbering are deliberate.
enum AaTouchAction {
  AA_TOUCH_DOWN(0),
  AA_TOUCH_UP(1),
  AA_TOUCH_MOVED(2),
  AA_TOUCH_POINTER_DOWN(5),
  AA_TOUCH_POINTER_UP(6);

  final int value;
  const AaTouchAction(this.value);

  static AaTouchAction fromValue(int value) => switch (value) {
    0 => AA_TOUCH_DOWN,
    1 => AA_TOUCH_UP,
    2 => AA_TOUCH_MOVED,
    5 => AA_TOUCH_POINTER_DOWN,
    6 => AA_TOUCH_POINTER_UP,
    _ => throw ArgumentError('Unknown value for AaTouchAction: $value'),
  };
}

/// One finger. `x` and `y` are in projected video pixels, not logical pixels and not
/// normalised: the phone is told the head unit has a touchscreen exactly the size of the
/// video it asked for, and it reads these against that. `id` identifies the finger
/// across a gesture and should be a small index, the way Android numbers pointers.
final class AaTouchPoint extends ffi.Struct {
  @ffi.Int32()
  external int id;

  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;
}

/// Which of the three PCM sinks a call is about, mirrored by AudioStream in
/// audio/audio_output.h and AndroidAutoAudioStream in Dart. Android Auto sends these as
/// three separate streams and leaves the mixing to the head unit, which is why they are
/// controlled separately rather than through one volume.
enum AaAudioStream {
  AA_AUDIO_STREAM_MEDIA(0),
  AA_AUDIO_STREAM_SYSTEM(1),
  AA_AUDIO_STREAM_SPEECH(2);

  final int value;
  const AaAudioStream(this.value);

  static AaAudioStream fromValue(int value) => switch (value) {
    0 => AA_AUDIO_STREAM_MEDIA,
    1 => AA_AUDIO_STREAM_SYSTEM,
    2 => AA_AUDIO_STREAM_SPEECH,
    _ => throw ArgumentError('Unknown value for AaAudioStream: $value'),
  };
}

/// A position fix, for aa_session_set_location.
///
/// Latitude and longitude are always read. The other four are skipped when they are NaN,
/// because every one of them has a meaningful zero: a bearing of zero is due north, an
/// altitude of zero is sea level and a speed of zero is standing still, so none of them
/// can double as "not known". A field left out is absent on the wire, which is not the
/// same as a field set to zero.
final class AaLocation extends ffi.Struct {
  @ffi.Double()
  external double latitude;

  @ffi.Double()
  external double longitude;

  /// Radius in metres of the circle the fix is somewhere in.
  @ffi.Double()
  external double accuracy_metres;

  @ffi.Double()
  external double altitude_metres;

  @ffi.Double()
  external double speed_mps;

  /// Direction of travel in degrees clockwise from north.
  @ffi.Double()
  external double bearing_degrees;
}

/// How the head unit describes itself to the phone during service discovery.
final class AaConfig extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int fps;

  @ffi.Int32()
  external int dpi;

  external ffi.Pointer<ffi.Char> head_unit_name;

  external ffi.Pointer<ffi.Char> car_model;

  external ffi.Pointer<ffi.Char> car_year;

  /// Directory holding headunit.crt and headunit.key. NULL uses the bundled pair.
  external ffi.Pointer<ffi.Char> certificate_path;

  /// Which sensors to advertise, an OR of AaSensor bits. Zero is read as the two that
  /// are not optional, AA_SENSOR_NIGHT_MODE and AA_SENSOR_DRIVING_STATUS: a head unit
  /// that answers neither leaves the phone with most of its interface locked.
  @ffi.Int32()
  external int sensors;

  /// Which metadata channels to advertise, an OR of `1 << AaMetadata`. Negative means
  /// the host app did not ask, and is read as navigation, media and telephony: the three
  /// the phone pushes without being asked, which cost the head unit nothing but a
  /// channel. Zero is a host app that wants none of them, which is a real choice.
  @ffi.Int32()
  external int metadata;
}

/// Called when the session changes state or has something to report.
///
/// Invoked from whatever thread the event originated on, so the Dart side must use a
/// NativeCallable.listener rather than an isolate local callback. `message` is heap
/// allocated by the core and ownership passes to the callee, which must hand it back to
/// aa_string_free once it has been copied into Dart. It is NULL when there is nothing
/// to say.
typedef AaEventCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int32 state, ffi.Pointer<ffi.Char> message)
      >
    >;

/// Called with one buffer of PCM, exactly as the phone sent it, before this head unit's
/// volume or ducking is applied. For a host app that wants to mix the audio itself;
/// pair it with aa_session_set_audio_output_enabled(session, 0).
///
/// Invoked from an audio writer thread, so the Dart side must use a
/// NativeCallable.listener. `data` is heap allocated by the core and ownership passes to
/// the callee, which must hand it back to aa_audio_buffer_free once it has been copied
/// into Dart. `stream` is an AaAudioStream.
typedef AaAudioCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Int32 stream,
          ffi.Pointer<ffi.Uint8> data,
          ffi.Int32 size,
          ffi.Int32 sample_rate,
          ffi.Int32 channels,
        )
      >
    >;
