name: android_auto_platform_interface
description: "Common platform interface for the android_auto plugin. Defines the contract every platform implementation has to fulfil."
version: 0.0.1
repository: https://github.com/mauznemo/FlutterAndroidAuto
publish_to: none

environment:
  sdk: ^3.13.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
